# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1976e56979e6aaaf0790d4bc223a9521b0a44124f9d95474d259f534f5516b3b0cac9521e8fa92655875a5a9d05965ac46b385ca30c0eabdb861caff7141255e

test:
  secret_key_base: 3af6cf0de31be2ee33d356abd5dda61e82db5a71d691aefc358e096405dd6ce5a5a8793bbbbe22a8d20d27a0248153436390fa93769935d3445638fe5622b52f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
